from pathlib import Path
import re


ROOT = Path(__file__).resolve().parent

REPLACEMENTS = [
    ("智能智能体人", "智能体"),
    ("智能体人", "智能体"),
    ("学习智能体人", "学习智能体"),
    ("从盒子里拿出来的Dreamer", "默认配置下的 Dreamer"),
    ("从盒子里拿出来的 Dreamer", "默认配置下的 Dreamer"),
    ("微薄的回报", "稀疏奖励"),
    ("正常化", "归一化"),
    ("强健技术", "稳健技术"),
    ("强力技术", "稳健技术"),
    ("一般算法", "通用算法"),
    ("应用域", "应用领域"),
    ("新域", "新领域"),
    ("预训", "预训练"),
    ("培训预算", "训练预算"),
    ("培训", "训练"),
    ("演员神经网络", "策略网络"),
    ("评论神经网络", "价值网络"),
    ("评论家", "critic"),
    ("国家值", "状态价值"),
    ("所学国家", "学得的状态"),
    ("世界模式", "世界模型"),
    ("转移模式", "转移模型"),
    ("远视任务", "长时程任务"),
    ("长视野", "长时程"),
    ("想象力MDP", "想象 MDP"),
    ("潜在的想象力", "潜在想象"),
    ("在想象力中", "在想象中"),
    ("通过想象力", "通过想象"),
    ("想象力训练", "想象训练"),
    ("想象力培训", "想象训练"),
    ("超出其预训练数据所显示的范围", "超越预训练数据所覆盖的行为范围"),
    ("专业专家算法", "专门算法"),
    ("不便性", "成本"),
    ("学习一种世界模型", "学习一个世界模型"),
    ("基因神经网络模型", "生成式神经网络模型"),
    ("革命变形自动编码器", "卷积变分自编码器"),
    ("回返", "回报"),
]


def normalize_punctuation(text: str) -> str:
    # Chinese prose generated by Argos often keeps ASCII punctuation.
    # Restrict conversions to punctuation next to CJK/LaTeX-citation text.
    text = re.sub(r"(?<=[\u4e00-\u9fffA-Za-z0-9}]),(?=[\u4e00-\u9fff])", "，", text)
    text = re.sub(r"(?<=[\u4e00-\u9fff])\.(?=(?:\s|$|\\\\))", "。", text)
    text = re.sub(r"(?<=\})(?=\.)\.(?=(?:\s|$|\\\\))", "。", text)
    text = re.sub(r"(?<=[\u4e00-\u9fff])。(?=[A-Za-z0-9])", "。", text)
    return text


def add_spaces_around_latin(text: str) -> str:
    # Add light spacing between Chinese and common Latin model/task names.
    tokens = [
        "DreamerV4",
        "DreamerV3",
        "DreamerV2",
        "Dreamer",
        "PlaNet",
        "MuZero",
        "Atari",
        "Minecraft",
        "MineRL",
        "PPO",
        "RL",
        "VAE",
        "RNN",
        "GRU",
        "MDP",
        "GPU",
        "CPU",
    ]
    for tok in tokens:
        text = re.sub(rf"(?<=[\u4e00-\u9fff])({re.escape(tok)})", r" \1", text)
        text = re.sub(rf"({re.escape(tok)})(?=[\u4e00-\u9fff])", r"\1 ", text)
    return text


def polish_text(text: str) -> str:
    for old, new in REPLACEMENTS:
        text = text.replace(old, new)
    text = normalize_punctuation(text)
    text = add_spaces_around_latin(text)
    text = re.sub(r" {2,}", " ", text)
    return text


def main() -> None:
    changed = []
    for path in ROOT.rglob("translation_latex/**/*.tex"):
        original = path.read_text(encoding="utf-8")
        updated = polish_text(original)
        if updated != original:
            path.write_text(updated, encoding="utf-8", newline="")
            changed.append(path)

    print(f"changed_files={len(changed)}")
    for path in changed:
        print(path.relative_to(ROOT))


if __name__ == "__main__":
    main()
